In [2]:
#Q1. Write a Python program to create a NumPy array with values ranging from 0 to 9 and print the elements from index 2 to index 5.
import numpy as np
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [6]:
#Q2. Write a Python program to create a NumPy array with the values [10, 20, 30, 40, 50] and print the entire array.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [11]:
#Q3, Write a Python program to convert a NumPy array of integers to a NumPy array of floats.
arr.astype('float64')
type(arr)


numpy.ndarray

In [14]:
#Q4. Write a Python program to create a 3x3 NumPy array and print the element at the second row and second column after transposing the array.
import numpy as np
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])

56


Problem Statement:

Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90º.

Input Format: (NOTE : No need to take the input explicitly, the input-handling code is already in place.)

A 2d numpy array
Output Format:

A 2d numpy array
Sample Input:

[[1 2 3] 
 [4 5 6]
 [7 8 9]]
Sample Output:

[[7 4 1]
 [8 5 2]
 [9 6 3]]

Note: Try Transpose / reversing.

In [15]:
import numpy as np
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat[::-1].transpose()
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Problem Statement:

Given a 2D numpy array, return array with its values in the column reversed.
Input Format:

A 2D numpy array
Output Format:

A 2D numpy array
Sample Input:

[[0, 1, 2], 
 [3, 4, 5], 
 [6, 7, 8]]
Sample Output:

[[2, 1, 0], 
 [5, 4, 3], 
 [8, 7, 6]]
P.S : Think about how we reverse list in python.

In [18]:
rev_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
rev_arr = rev_arr[:,::-1]
print(rev_arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [19]:
#Q5. Write a Python program to create a NumPy array with the values [1, 2, 3, 4] and print the sum of the elements at index 2 and index -2.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])

6


a. Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

b. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

Which options correctly answer questions a and b?

In [20]:
np.arange(22,71,2)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [21]:
np.arange(21, 72, 2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

Problem statement:

Given an array, return the shape and dimension of the array.
Input Format:

A numpy array
Output Format:

A Tuple (shape, dim)
Sample Input:

[0 1 2 3 4 5]
Sample Output:

((6,), 1)

In [23]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape
dim = arr.ndim
print("Shape of the array:", shape)
print("Number of dimensions:", dim)
print((shape, dim))


Shape of the array: (2, 3)
Number of dimensions: 2
((2, 3), 2)


Problem Statement:

Given a 1D array, return the first and last elements from the array.
Input Format: (NOTE : No need to take the input explicitly, the input-handling code is already in place.)

A 1D numpy array
Output Format:

A tuple (first_element, last_element)
Sample Input:

[0, 1, 2, 3, 4, 5]
Sample Output:

(0, 5)

In [24]:
arr = np.array([10, 20, 30, 40, 50])
first_element = arr[0]
last_element = arr[-1]
print("First element:", first_element)
print("Last element:", last_element)
print((first_element, last_element))

First element: 10
Last element: 50
(10, 50)


Create a sequence of a given length from a given start point, where the difference between 2 consecutive elements of the expected sequence is also given as step.

Input Format:

One line of input will have 3 space-separated integers consisting of start, length of sequence and step between two continuous elements of the sequence.
Output Format:

A numpy array of integers
Sample Input:

5 10 3
Sample Output:

[5 8 11 14 17 20 23 26 29 32]
Sample explanation:

Start of the sequence = 5, length of the sequence = 10 and step = 3.

First point would be the start point only, second point = start + 1*step = 5 + 1*3 =8, ....... 10th point = start + (10-1)*step = 5 + 9*3 = 32


Note: You can use either .arange() or .linspace() to solve this question.

In [25]:
start = 5
step = 3
length = 10
arr = np.arange(start,start + (step*length),step)
print(arr)

[ 5  8 11 14 17 20 23 26 29 32]


Problem Statement:

Given the start, end, and the stepsize return a numpy array sequence in given range with the specified stepsize.
Input Format:

One line of input will have 3 space-separated numbers consisting of start, end of sequence and step.
Output Format:

A numpy array with elements rounded off to 2 decimal places.
Sample Input:

5 7 0.5
Sample Output:

[5 5.5 6 6.5]
Note: To round off the numpy array, use np.round()

P.s: Recall that we can have float step size in numpy array

In [26]:
start = 1.5
end = 5.5
step = 0.5

arr = np.array(np.round(np.arange(start,end,step),2))

print(arr)

[1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [ ]:
#Q6. Write a Python program to create a NumPy array with the values [1, 2, 3, 4, 5, 6, 7, 8] and replace every second element with the values from another array [10, 20, 30, 40].
arr = np.array([1,2,3,4,5,6,7,8])
arr[::2] = range(10,50,10)
print(arr)

[10  2 20  4 30  6 40  8]


Given a numpy array,

arr : array([10, 12, 15, 17, 2, 5, 4, 6])

Which of the following is NOT the correct way to access the values at even indices (0,2,4...)?

- [x] arr[0,2,4,6]

- [ ] arr[[0,2,4,6]]

- [ ] arr[::2]

In [29]:
arr = np.array([10, 12, 15, 17, 2, 5, 4, 6])

In [30]:
arr[0,2,4,6]

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [31]:
arr[[0,2,4,6]]

array([10, 15,  2,  4])

In [32]:
arr[::2]

array([10, 15,  2,  4])