In [1]:
import numpy as np

### Create 1D Array

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Create a Boolean Array

In [5]:
np.full((9),True,dtype=bool).reshape(3,3) # Way 1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
np.full((3,3),True,dtype=bool) #way 2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
np.ones((3,3),dtype=bool) # way 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
np.ones((9),dtype=bool).reshape(3,3) #way 4

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### extract items that satisfy a given condition from 1D array

extract all the odd numbers from array 1,2,3,.....9


In [12]:
arr = np.arange(10)

In [13]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

### replace items that satisfy a condition with another value in numpy array
replace all the odd numbers in arr with -1

In [14]:
arr = np.arange(10)

In [15]:
arr[arr%2!=0] = -1

In [16]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### replace items that satisfy a condition without affecting the original array

Replace all odd numbers in arr with -1 without changing arr

In [17]:
arr = np.arange(10)

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy[arr_copy%2!=0] = -1

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr_copy

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### reshape an array


Convert a 1D array to a 2D array with 2 rows

In [22]:
arr = np.arange(10)

In [23]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### stack two arrays vertically

Stack arrays a and b vertically

In [24]:
a = np.arange(10).reshape(2,-1)

In [25]:
b = np.arange(10,20).reshape(2,-1)

In [26]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### stack two arrays horizontally

Stack the arrays a and b horizontally.

In [29]:
b = np.arange(10,20).reshape(2,-1)

In [30]:
a = np.arange(10).reshape(2,-1)

In [31]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

### generate custom sequences in numpy without hardcoding

Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

#### Input: a = np.array([1,2,3])
#### Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [32]:
a = np.array([1,2,3])

In [33]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [38]:
np.r_[a[0:1],a[1:2]]

array([1, 2])

In [39]:
np.c_[a[0:1],a[1:2]]

array([[1, 2]])

In [41]:
np.r_[np.repeat(a,3),np.tile(a,3)]  # Way 1

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
np.hstack((np.repeat(a,3),np.tile(a,3))) # Way 2

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### get the common items between two python numpy arrays

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [45]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [47]:
np.intersect1d(a,b)

array([2, 4])

### remove from one array those items that exist in another

From array a remove all items present in array b


In [49]:
a = np.array([1,2,3,4,5])

In [50]:
b = np.array([5,6,7,8,9])

In [53]:
np.subtract(a,b) # not a solution

array([-4, -4, -4, -4, -4])

In [54]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### get the positions where elements of two arrays match

In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [58]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [59]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### extract all numbers between a given range from a numpy array

 Get all items between 5 and 10 from a.

In [60]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [62]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])