In [2]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

1.0


In [3]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

21


In [4]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [5]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

Problem Statement:

Given an array of marks, return the array only containing elements with marks > 40
Input Format:

A 1D numpy array
Output Format:

A 1D numpy array
Sample Input:

[85, 18, 2, 57, 65, 44]
Sample Output:

[85, 57, 65, 44]

In [6]:
marks = np.array([85, 18, 2, 57, 65, 44])
mask = marks>40
print(marks[mask])

[85 57 65 44]


Problem Statement:

Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:

1. the second to the fourth row of the original array,

2. the elements in these rows should be from the last three columns of the corresponding rows of the original array,

3. the rows should be in reversed order.

Sample Input:

[[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]]
Sample Output:

array([[13, 14, 15],  
       [ 9, 10, 11], 
       [ 5,  6,  7]])
Input Format: (NOTE : No need to take the input explicitly, the input-handling code is already in place.)

A 2D list
Output Format:

A 2D numpy array
Note:

This question can be solved using negative indexing and slicing

Problem Statement:

Given a numpy array and target value k,

Return True if all elements of array satisfy all below given conditions

Multiple of 2
Greater than k
Input Format:

The input has two lines
First line is the array
Second line is the integer value k
Output Format:

Boolean value i.e. True or False
Sample Input:

[0, 1, 2, 3, 4, 5, 6, 7, 8]
3
Sample Output:

False
Sample Input:

[8, 12, 16, 20]
4
Sample Output:

True
Note: Recall logical functions in numpy

In [7]:
arr = np.array([2,4,6,8,10,12,14,16,18,20])
k = 7   
mask = ((arr%2==0) & (arr>k))
result = np.all(mask)
print(result)


False


In [8]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [9]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [10]:
a.shape

(3, 4)

arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 

Which of the following are vectorized code(s) for array operations?

In [11]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 
for i in range(len(arr1)): 
    arr3[i] = arr1[i] * arr2[i] 
print(arr3)

[ 4.  4.  3. 18.  9.  4.]


In [12]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 
arr3 = arr1*arr2
arr3

array([ 4,  4,  3, 18,  9,  4])

In [13]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 
for i in range(len(arr1)): 
    if(arr1[i] < 0 ): 
        arr1[i] = -1 
    else: 
        arr1[i] = 1
print(arr1)

[1 1 1 1 1 1]


In [14]:
arr1 = np.array([1,2,3,6,3,2]) 

arr2 = np.array([4,2,1,3,3,2]) 

arr3 = np.zeros(len(arr1)) 
np.where(arr1 > 0, 1, -1)

array([1, 1, 1, 1, 1, 1])

In [15]:
import numpy as np
arr = np.arange(0,2,0.5) * 2
if np.all(arr <= 0.6):
    print("condition satisfies")
else:
    print("condition doesn't satisfy") 

condition doesn't satisfy


Problem Description:

Given a list of birds and their corresponding age, calculate the mean age of the Crane bird (rounded off to 2 decimal points)
Input Format:

Two 1D array list i.e. bird array and age array
Output Format:

Float value representing mean age of crane birds
Sample Input:

birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
Sample Output:

4.75
Note:

To round off the result, use np.round()
Documentation link: np.round()

In [16]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])


mean_age = np.mean(age)
    
## STEP1. Create mask to get Crane birds from birds array
mask = birds == "Cranes"
    
## STEP2. Get the age of crane birds
    
crane_ages = age[mask]
    
## STEP 3. Calculate mean age of crane birds
    
mean_age = np.mean(crane_ages)
    
## STEP 4. Round off the mean age to 2 decimal points
    
mean_age = np.round(mean_age,2)
    
    
print(mean_age)

4.75


Given the NumPy array arr, which of the following line of code will return the expected output?

```python
array ([[4,6,8,10],
 [2,14,6,10],
 [4,16,12,18],
 [22,46,24,38]])
 ```

In [17]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [18]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [19]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [20]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])